### ISSUE TITLE
Use release section

### ISSUE THREAD

**Issue by rancidfrog** [GroovinChip/CallManager#1]
Having releases in release section is useful.
Also, attaching apk to release section would be great

**Comment by GroovinChip** [comment]
Thanks very much for your suggestion! 

I've considered it, but since I will be posting apk's on my Discord group, and the apk is available through XDA Labs, I'm not sure it's warranted. What would be an advantage of posting it here?

**Comment by GroovinChip** [comment]
Using release section now
